###
### Core configuration for Jekyll, used to build the documentation
### set for the Leeds Beckett tools repository.
###
### See [the core documentation](https://jekyllrb.com/docs/configuration/options/)
### for the options used in this file.
###
### NOTE: The documentation is built (and deployed) using an action
###       on Github. Any changes to this file also need to be checked
###       to ensure the public pages don't break...
###

##
## Page Settings
##

# Colours and definitions for the page call-outs
callouts:
  warning:
    title: Warning
    color: signal-orange
  note:
    title: Note
    color: signal-brown

# Force the use of page anchors: needed for heading mods
# using [jekyll-anchor-headings ](https://github.com/allejo/jekyll-anchor-headings)
heading_anchors: true

# Set the variable for the page colour
section_color: "#DD0000"

##
## Page Categories
##

# Root directory for the collections of source
# documents
collections_dir: docs

# Site collection categories
collections:
  explanation:
    output: true
  howto:
    output: true
  reference:
    output: true
  tutorial:
    output: true

just_the_docs:
  collections:
    tutorial:
      name: Tutorials
      nav_fold: false
    howto:
      name: How To
      nav_fold: false
    explanation:
      name: Explanations
      nav_fold: false
    reference:
      name: References
      nav_fold: false

##
## Site Defaults
## 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "lbu"

baseurl: /lb_tools

##
## Site Settings
## 

title: Leeds Beckett Tools
logo: https://dlove24.github.io/lb_tools/assets/LB_Logo.png

description: >- # this means to ignore newlines until "baseurl:"
  Tools, documentation and other resources for Electronic, Electrical and Robotics Engineering modules and courses at Leeds Beckett University

color_scheme: lbu

##
## Build Settings
##

# Exclude directories from processing
exclude:
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - common/
  - styles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

include:
  - assets/

# Allow following of symbolic links, so that we don't have to
# copy all the documentation to the 'docs' directory
safe: false

# Theme
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed

##
## Serve Command Options
##

# Listen on port 8080
port: 8080
    
# Enable live reload
livereload: true


