###
### Site Settings
### 

title: Leeds Beckett Electronics and Robotics Tools

description: >- # this means to ignore newlines until "baseurl:"
  Tools, documentation and other resources for Electronic, Electrical and Robotics Engineering modules and courses at Leeds Beckett University

###
### Build
###

# Root directory for the source
source: docs

# Exclude directories from processing
exclude:
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - common/
  - styles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

# Theme
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed

###
### Serve Command Options
###

# Listen on port 8080
port: 8080
    
# Enable live reload
livereload: true


