###
### Core configuration for Jekyll, used to build the documentation
### set for the Leeds Beckett tools repository.
###
### See [the core documentation](https://jekyllrb.com/docs/configuration/options/)
### for the options used in this file.
###
### NOTE: The documentation is built (and deployed) using an action
###       on Github. Any changes to this file also need to be checked
###       to ensure the public pages don't break...
###

##
## Site Settings
## 

title: Leeds Beckett Tools

description: >- # this means to ignore newlines until "baseurl:"
  Tools, documentation and other resources for Electronic, Electrical and Robotics Engineering modules and courses at Leeds Beckett University

color_scheme: lbu

##
## Build
##

# Root directory for the source
source: docs

# Exclude directories from processing
exclude:
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - common/
  - styles/
  - Gemfile
  - Gemfile.lock
  - node_modules/

# Allow following of symbolic links, so that we don't have to
# copy all the documentation to the 'docs' directory
safe: false

# Theme
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed

##
## Serve Command Options
##

# Listen on port 8080
port: 8080
    
# Enable live reload
livereload: true


